export const photos = [
  {
    id: 1,
    height: 1800,
    width: 3200,
    src: "/photos/1.jpg",
    title: "Festive lights of Durga Puja in Kolkata",
    category: "Festivals",
  },
  {
    id: 2,
    height: 720,
    width: 1080,
    src: "/photos/2.jpg",
    title: "Sam Sand Dunes of Rajasthan",
    category: "Travel",
  },
  {
    id: 3,
    height: 637,
    width: 960,
    src: "/photos/3.jpg",
    title: "To a new beginning",
    category: "Weddings",
  },
  {
    id: 4,
    height: 637,
    width: 960,
    src: "/photos/4.jpg",
    title: "The welcome",
    category: "Weddings",
  },
  {
    id: 5,
    height: 3235,
    width: 2848,
    src: "/photos/5.jpg",
    title: "Fun and frolic, the childhood reflection",
    category: "Kids",
  },
  {
    id: 6,
    height: 2262,
    width: 4288,
    src: "/photos/6.jpg",
    title: "Annapurna",
    category: "Festivals",
  },
  {
    id: 7,
    height: 1328,
    width: 2000,
    src: "/photos/7.jpg",
    title: "Table decors",
    category: "Product",
  },
  {
    id: 8,
    height: 1069,
    width: 1600,
    src: "/photos/8.jpg",
    title: "Smile",
    category: "Kids",
  },
  {
    id: 9,
    height: 2848,
    width: 4288,
    src: "/photos/9.jpg",
    title: "Musicians rock the stage",
    category: "Events",
  },
  {
    id: 10,
    height: 1333,
    width: 2000,
    src: "/photos/10.jpg",
    title: "The world is beauiful with you",
    category: "Weddings",
  },
  {
    id: 11,
    height: 3000,
    width: 2000,
    src: "/photos/11.jpg",
    title: "Fire",
    category: "Events",
  },
  {
    id: 12,
    height: 4288,
    width: 2848,
    src: "/photos/12.jpg",
    title:
      "Cycle Satyagraha, a walk against cycling ban on the streets of Kolkata",
    category: "Photojournalism",
  },
  {
    id: 13,
    height: 2652,
    width: 4165,
    src: "/photos/13.jpg",
    title: "Hand pulled rickshaws of Kolkata",
    category: "Street",
  },
  {
    id: 14,
    height: 4000,
    width: 6000,
    src: "/photos/14.jpg",
    title: "Shower the blessings upon us",
    category: "Weddings",
  },
  {
    id: 15,
    height: 1125,
    width: 2000,
    src: "/photos/15.jpg",
    title: "Monsoon and Konkan Railway, the made for each other couple",
    category: "Travel",
  },
  {
    id: 16,
    height: 2418,
    width: 3643,
    src: "/photos/16.jpg",
    title: "Early morning at Kolkata Maidan",
    category: "Travel",
  },
  {
    id: 17,
    height: 1080,
    width: 1080,
    src: "/photos/17.jpg",
    title: "Stairway to heaven",
    category: "Nature",
  },
  {
    id: 18,
    height: 2320,
    width: 3544,
    src: "/photos/18.jpg",
    title: "A lovestory",
    category: "Weddings",
  },
  {
    id: 19,
    height: 898,
    width: 3648,
    src: "/photos/19.jpg",
    title: "Cars line up near Rohtang Pass",
    category: "Travel",
  },
  {
    id: 20,
    height: 525,
    width: 794,
    src: "/photos/20.jpg",
    title: "Ghats of Varanasi",
    category: "Travel",
  },
  {
    id: 21,
    height: 960,
    width: 960,
    src: "/photos/21.jpg",
    title: "Dazzling",
    category: "Nature",
  },
  {
    id: 22,
    height: 2442,
    width: 3648,
    src: "/photos/22.jpg",
    title: "Cars stuck in heavy blizzard near Rohtang Pass",
    category: "Photojournalism",
  },
  {
    id: 23,
    height: 6000,
    width: 4000,
    src: "/photos/23.jpg",
    title: "Karnataka weds Kerala",
    category: "Weddings",
  },
  {
    id: 24,
    height: 2340,
    width: 4160,
    src: "/photos/24.jpg",
    title: "Jaisalmer's living fort, the Golden Fort",
    category: "Travel",
  },
  {
    id: 25,
    height: 576,
    width: 960,
    src: "/photos/25.jpg",
    title: "Fiery sunset over Vashi bridge",
    category: "Nature",
  },
  {
    id: 26,
    height: 608,
    width: 1080,
    src: "/photos/26.jpg",
    title:
      "A man walks with an umbrella as it rains inside Infosys Pune campus",
    category: "Nature",
  },
  {
    id: 27,
    height: 2340,
    width: 4160,
    src: "/photos/27.jpg",
    title: "The lone boat at Tapola",
    category: "Travel",
  },
  {
    id: 28,
    height: 960,
    width: 637,
    src: "/photos/28.jpg",
    title: "Wall paintings adorn the buildings on Chapel Road, Mumbai",
    category: "Streets",
  },
  {
    id: 29,
    height: 583,
    width: 960,
    src: "/photos/29.jpg",
    title: "Up above and also high",
    category: "Architecture",
  },
  {
    id: 30,
    height: 673,
    width: 1024,
    src: "/photos/30.jpg",
    title: "Mumbai, the city that never stops",
    category: "Streets",
  },
  {
    id: 31,
    height: 1196,
    width: 2500,
    src: "/photos/31.jpg",
    title: "Bright mustard field",
    category: "Nature",
  },
  {
    id: 32,
    height: 2736,
    width: 3648,
    src: "/photos/32.jpg",
    title: "Citizens enjoying tasty breakfast",
    category: "Streets",
  },
  {
    id: 33,
    height: 1120,
    width: 2000,
    src: "/photos/33.jpg",
    title: "Cushions",
    category: "Product",
  },
  {
    id: 34,
    height: 1333,
    width: 2000,
    src: "/photos/34.jpg",
    title: "Expressing",
    category: "Weddings",
  },
  {
    id: 35,
    height: 3648,
    width: 2736,
    src: "/photos/35.jpg",
    title: "A man poses for the camera at Nakhoda Mosque",
    category: "Portrait",
  },
  {
    id: 36,
    height: 1489,
    width: 2260,
    src: "/photos/36.jpg",
    title: "A fairytale",
    category: "Weddings",
  },
  {
    id: 37,
    height: 2736,
    width: 3648,
    src: "/photos/37.jpg",
    title: "Idols under making in Kumartuli potters' colony in north Kolkata",
    category: "Festivals",
  },
  {
    id: 38,
    height: 3120,
    width: 4160,
    src: "/photos/38.jpg",
    title: "A beautiful sunset in Mangalore",
    category: "Travel",
  },
  {
    id: 39,
    height: 2736,
    width: 3648,
    src: "/photos/39.jpg",
    title: "Five sisters",
    category: "Travel",
  },
  {
    id: 40,
    height: 2340,
    width: 4160,
    src: "/photos/40.jpg",
    title: "Mumbai Pune Expressway",
    category: "Travel",
  },
  {
    id: 41,
    height: 1333,
    width: 2000,
    src: "/photos/41.jpg",
    title: "A life with you and me",
    category: "Weddings",
  },
  {
    id: 42,
    height: 510,
    width: 960,
    src: "/photos/42.jpg",
    title: "Rituals of Durga Puja on the ghats of Hoogly river",
    category: "Festivals",
  },
  {
    id: 43,
    height: 2034,
    width: 3486,
    src: "/photos/43.jpg",
    title: "Silent music",
    category: "Product",
  },
  {
    id: 44,
    height: 960,
    width: 768,
    src: "/photos/44.jpg",
    title: "Colors of monsoon",
    category: "Nature",
  },
  {
    id: 45,
    height: 1558,
    width: 3018,
    src: "/photos/45.jpg",
    title: "Patterns",
    category: "Architecture",
  },
  {
    id: 46,
    height: 1291,
    width: 1941,
    src: "/photos/46.jpg",
    title: "Half lighted",
    category: "Architecture",
  },
  {
    id: 47,
    height: 607,
    width: 1080,
    src: "/photos/47.jpg",
    title: "Tea plantations in Munnar",
    category: "Travel",
  },
  {
    id: 48,
    height: 2340,
    width: 4160,
    src: "/photos/48.jpg",
    title: "Winter mornings",
    category: "Nature",
  },
  {
    id: 49,
    height: 2340,
    width: 4160,
    src: "/photos/49.jpg",
    title: "The city of Jodhpur",
    category: "Travel",
  },
  {
    id: 50,
    height: 1334,
    width: 2000,
    src: "/photos/50.jpg",
    title: "Happiness",
    category: "Weddings",
  },
  {
    id: 51,
    height: 3648,
    width: 2736,
    src: "/photos/51.jpg",
    title: "Smile, it is good for health",
    category: "Portrait",
  },
  {
    id: 52,
    height: 810,
    width: 1080,
    src: "/photos/52.jpg",
    title: "Kerala ayurvedic water",
    category: "Food",
  },
  {
    id: 53,
    height: 648,
    width: 1080,
    src: "/photos/53.jpg",
    title: "Lights",
    category: "Product",
  },
  {
    id: 54,
    height: 810,
    width: 1080,
    src: "/photos/54.jpg",
    title: "Letter boxes awaiting mails",
    category: "Streets",
  },
  {
    id: 55,
    height: 2848,
    width: 4288,
    src: "/photos/55.jpg",
    title: "Happy faces of Eid",
    category: "Festivals",
  },
];
